DROP DATABASE pamnss;
CREATE DATABASE IF NOT EXISTS pamnss;
USE pamnss;

CREATE TABLE groups (
  _group BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY
, name VARCHAR(64) NOT NULL
, gid BIGINT UNSIGNED NOT NULL
, UNIQUE INDEX (gid, name)
, INDEX (name)
) CHARACTER SET 'ASCII';

CREATE TABLE users (
  _user BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY
, name VARCHAR(64) UNIQUE NOT NULL
, uid BIGINT UNSIGNED NOT NULL
, _group BIGINT UNSIGNED NOT NULL
, FOREIGN KEY (_group) REFERENCES groups (_group) ON DELETE CASCADE ON UPDATE CASCADE
, homedir VARCHAR(255) NOT NULL
, shell VARCHAR(255) NOT NULL
, INDEX (uid)
) CHARACTER SET 'ASCII';

CREATE TABLE shadow (
  _shadow BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY
, _user BIGINT UNSIGNED NOT NULL
, FOREIGN KEY (_user) REFERENCES users (_user) ON DELETE CASCADE ON UPDATE CASCADE
, shadow VARCHAR(255) NOT NULL
) CHARACTER SET 'ASCII';

CREATE TABLE membership (
  _user BIGINT UNSIGNED NOT NULL
, FOREIGN KEY (_user) REFERENCES users (_user) ON DELETE CASCADE ON UPDATE CASCADE
, _group BIGINT UNSIGNED NOT NULL
, FOREIGN KEY (_group) REFERENCES groups (_group) ON DELETE CASCADE ON UPDATE CASCADE
, PRIMARY KEY (_user, _group)
, UNIQUE INDEX (_group, _user)
) CHARACTER SET 'ASCII';
