CREATE DATABASE IF NOT EXISTS pamnss;
USE pamnss;

CREATE TABLE pamnss.users (_ BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(64) UNIQUE NOT NULL, uid BIGINT UNSIGNED NOT NULL, gid BIGINT UNSIGNED NOT NULL, gecos VARCHAR(255), homedir VARCHAR(255) NOT NULL, shell VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, lastpwchange DATETIME, flags BIGINT UNSIGNED NOT NULL, INDEX (uid), INDEX (gid), INDEX(password)) CHARACTER SET 'ASCII';

CREATE TABLE users (
  _ BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(64) UNIQUE NOT NULL,
  UID BIGINT UNSIGNED NOT NULL,
  gid BIGINT UNSIGNED NOT NULL,
  gecos VARCHAR(255),
  homedir VARCHAR(255) NOT NULL,
  shell VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  lastpwchange DATETIME,
  flags BIGINT UNSIGNED NOT NULL,
  INDEX (UID),
  INDEX (gid),
  INDEX(password)
) CHARACTER SET 'ASCII';

CREATE TABLE group (
  _ BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(64) UNIQUE NOT NULL,
  gid BIGINT UNSIGNED NOT NULL,
  members VARBINARY(248) NOT NULL,
  INDEX (gid)
) CHARACTER SET 'ASCII';

GRANT SELECT (_,name,uid,gid,gecos,homedir,shell) ON pamnss.users TO 'nss-user'@localhost
GRANT SELECT ON pamnss.group TO 'nss-user'@localhost;

GRANT SELECT ON pamnss.users TO 'nss-root'@localhost;
GRANT SELECT ON pamnss.group TO 'nss-root'@localhost;
